# Generated by Django 5.1.6 on 2025-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '多个用户信息'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='salt',
            field=models.CharField(default=1, max_length=256, verbose_name='盐'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
