# Generated by Django 5.1.6 on 2025-03-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='UnKnown', max_length=100),
        ),
    ]
