export const cities = {
    hot: [
        { name: '上海', code: 'SHA' },
        { name: '北京', code: 'BJS' },
        { name: '成都', code: 'CDE' },
        { name: '广州', code: 'CAN' },
        { name: '三亚', code: 'SYX' },
        { name: '深圳', code: 'SZX' },
        { name: '重庆', code: 'CKG' },
        { name: '杭州', code: 'HGH' },
        { name: '昆明', code: 'KMG' },
        { name: '西安', code: 'SIA' },
        { name: '海口', code: 'HAK' },
        { name: '哈尔滨', code: 'HRB' },
        { name: '乌鲁木齐', code: 'URC' },
        { name: '长沙', code: 'CSX' },
        { name: '厦门', code: 'XMN' },
        { name: '沈阳', code: 'SHE' },
        { name: '武汉', code: 'WUH' },
        { name: '天津', code: 'TSN' },
        { name: '青岛', code: 'TAO' },
    ],
    ABCDEF: [
        { character: 'A', cities: [
            { name: '中国澳门' },
            { name: '阿里' },
            { name: '安顺' },
            { name: '阿克苏' },
            { name: '阿勒泰' },
            { name: '安康' },
            { name: '鞍山' },
            { name: '安顺' },
            { name: '安阳' },
            { name: '阿尔山' },
            { name: '阿拉尔' },
            { name: '阿拉善左' },
            { name: '阿拉善右' }
        ] },
        { character: 'B', cities: [
            { name: '北京' },
            { name: '包头' },
            { name: '北海' },
            { name: '保山' },
            { name: '白山' },
            { name: '白城' },
            { name: '百色' },
            { name: '博乐' },
            { name: '布尔津' },
            { name: '巴彦淖尔' },
            { name: '巴中' },
            { name: '毕节' },
        ] },
        { character: 'C', cities: [
            { name: '重庆' },
            { name: '成都' },
            { name: '长治' },
            { name: '长春' },
            { name: '常德' },
            { name: '赤峰' },
            { name: '长沙' },
            { name: '朝阳' },
            { name: '常州' },
            { name: '池州' },
            { name: '承德' },
            { name: '昌都' },
            { name: '郴州' },
            { name: '毕节' },
            { name: '沧源' },
        ] },
        { character: 'D', cities: [
            { name: '大连' },
            { name: '敦煌' },
            { name: '大理' },
            { name: '迪庆' },
            { name: '大同' },
            { name: '丹东' },
            { name: '大庆' },
            { name: '东营' },
            { name: '稻城' },
            { name: '达州' },
            { name: '德令哈' },
        ] },
        { character: 'E', cities: [
            { name: '恩施' },
            { name: '鄂州' },
            { name: '鄂尔多斯' },
            { name: '额济纳旗' },
            { name: '二连浩特' },

        ]},
        { character: 'F', cities: [
            { name: '佛山' },
            { name: '富蕴' },
            { name: '阜阳' },
            { name: '福州' },
            { name: '抚远' },

        ]}
        // 其他字母分组...
    ],
    GHIJ: [
        { character: 'G', cities: [
            { name: '广州' },
            { name: '桂林' },
            { name: '贵阳' },
            { name: '格尔木' },
            { name: '甘南' },
            { name: '甘孜' },
            { name: '甘南' },
            { name: '广安' },
           { name: '广元' },
        ]}
    ]
    // 其他字母分组...
};