export const cities = {
    hot: [
        { name: '上海', code: 'SHA' },
        { name: '北京', code: 'BJS' },
        { name: '成都', code: 'CDE' },
        { name: '广州', code: 'CAN' },
        { name: '三亚', code: 'SYX' },
        { name: '深圳', code: 'SZX' },
        { name: '重庆', code: 'CKG' },
        { name: '杭州', code: 'HGH' },
        { name: '昆明', code: 'KMG' },
        { name: '西安', code: 'SIA' },
        { name: '海口', code: 'HAK' },
        { name: '哈尔滨', code: 'HRB' },
        { name: '乌鲁木齐', code: 'URC' },
        { name: '长沙', code: 'CSX' },
        { name: '厦门', code: 'XMN' },
        { name: '沈阳', code: 'SHE' },
        { name: '武汉', code: 'WUH' },
        { name: '天津', code: 'TSN' },
        { name: '青岛', code: 'TAO' },
    ],
    ABCDEF: [
        { character: 'A', cities: [
            { name: '中国澳门' },
            { name: '阿里' },
            { name: '安顺' },
            { name: '阿克苏' },
            { name: '阿勒泰' },
            { name: '安康' },
            { name: '鞍山' },
            { name: '安顺' },
            { name: '安阳' },
            { name: '阿尔山' },
            { name: '阿拉尔' },
            { name: '阿拉善左' },
            { name: '阿拉善右' }
        ] },
        { character: 'B', cities: [
            { name: '北京' },
            { name: '包头' },
            { name: '北海' },
            { name: '保山' },
            { name: '白山' },
            { name: '白城' },
            { name: '百色' },
            { name: '博乐' },
            { name: '布尔津' },
            { name: '巴彦淖尔' },
            { name: '巴中' },
            { name: '毕节' },
        ] },
        { character: 'C', cities: [
            { name: '重庆' },
            { name: '成都' },
            { name: '长治' },
            { name: '长春' },
            { name: '常德' },
            { name: '赤峰' },
            { name: '长沙' },
            { name: '朝阳' },
            { name: '常州' },
            { name: '池州' },
            { name: '承德' },
            { name: '昌都' },
            { name: '郴州' },
            { name: '毕节' },
            { name: '沧源' },
        ] },
        { character: 'D', cities: [
            { name: '大连' },
            { name: '敦煌' },
            { name: '大理' },
            { name: '迪庆' },
            { name: '大同' },
            { name: '丹东' },
            { name: '大庆' },
            { name: '东营' },
            { name: '稻城' },
            { name: '达州' },
            { name: '德令哈' },
        ] },
        { character: 'E', cities: [
            { name: '恩施' },
            { name: '鄂州' },
            { name: '鄂尔多斯' },
            { name: '额济纳旗' },
            { name: '二连浩特' },

        ]},
        { character: 'F', cities: [
            { name: '佛山' },
            { name: '富蕴' },
            { name: '阜阳' },
            { name: '福州' },
            { name: '抚远' },

        ]}
        // 其他字母分组...
    ],
    GHIJ: [
        { character: 'G', cities: [
            { name: '广州' },
            { name: '桂林' },
            { name: '贵阳' },
            { name: '格尔木' },
            { name: '甘南' },
            { name: '甘孜' },
            { name: '甘南' },
            { name: '广安' },
            { name: '广元' },
            { name: '广饶' },
            { name: '赣州' },
            { name: '固原' },
            { name: '中国高雄' },
            { name: '果洛' },
        ]},
        {  character: 'H', cities: [
            { name: '哈尔滨' },
            { name: '杭州' },
            { name: '黄山' },
            { name: '海口' },
            { name: '呼和浩特' },
            { name: '汉中' },
            { name: '海拉尔' },
            { name: '邯郸' },
            { name: '合肥' },
            { name: '黑河' },
            { name: '怀化' },
            { name: '哈密' },
            { name: '和田' },
            { name: '衡阳' },
            { name: '惠州' },
            { name: '淮安' },
            { name: '菏泽' },
            { name: '花土沟' },
            { name: '和静' },
            { name: '河池' },
            { name: '霍林郭勒' },
            { name: '中国花莲' },
            { name: '红原' },
        ]},
        {  character: 'J', cities: [
            { name: '九江' },
            { name: '九寨沟' },
            { name: '济南' },
            { name: '鸡西' },
            { name: '景德镇' },
            { name: '井冈山' },
            { name: '济宁' },
            { name: '嘉峪关' },
            { name: '锦州' },
            { name: '荆州' },
            { name: '揭阳' },
            { name: '加格达奇' },
            { name: '金昌' },
            { name: '建三江' },
            { name: '中国嘉义' },
            { name: '中国金门' },
        ]},
    ],
    KLMN: [
        { character: 'K', cities: [
            { name: '昆明' },
            { name: '喀什' },
            { name: '克拉玛依' },
            { name: '库车' },
            { name: '库尔勒' },
            { name: '凯里' },
            { name: '康定'},
        ]},
        { character: 'L', cities: [
            { name: '丽江' },
            { name: '拉萨' },
            { name: '兰州' },
            { name: '林芝' },
            { name: '龙岩' },
            { name: '临汾' },
            { name: '洛阳' },
            { name: '连云港' },
            { name: '柳州'},
            { name: '泸州'},
            { name: '临沂'},
            { name: '六盘水'},
            { name: '临沧'},
            { name: '荔波'},
            { name: '阆中'},
            { name: '黎平'},
            { name: '澜沧'},
            { name: '吕梁'},
            { name: '陇南'},
        ]},
        { character: 'M', cities: [
            { name: '牡丹江' },
            { name: '漠河' },
            { name: '绵阳' },
            { name: '满洲里' },
            { name: '茅台' },
            { name: '梅州' },
            { name: '芒市' },
            { name: '茂名' },
        ]},
        { character: 'N', cities: [
            { name: '南京' },
            { name: '南通' },
            { name: '宁波' },
            { name: '南昌' },
            { name: '南充' },
            { name: '南宁' },
            { name: '南阳' },
            { name: '宁蒗' },
            { name: '中国南竿' },
        ]}
    ],
    PQRSTUVW : [
        {  character: 'P', cities: [
            { name: '攀枝花' },
            { name: '普洱' },
            { name: '普兰' },
        ]},
        { character: 'Q', cities: [
            { name: '青岛' },
            { name: '琼海' },
            { name: '秦皇岛' },
            { name: '齐齐哈尔' },
            { name: '且末' },
            { name: '庆阳' },
            { name: '泉州' },
            { name: '衢州' },
            { name: '祁连' },
            { name: '奇台' },
            { name: '黔江' },
        ]},
        { character: 'R', cities: [
            { name: '日喀则' },
            { name: '日照' },
            { name: '若羌' },
        ]},
        { character: 'S', cities: [
            { name: '上海' },
            { name: '深圳' },
            { name: '三亚' },
            { name: '上饶' },
            { name: '韶关' },
            { name: '石河子' },
            { name: '石家庄' },
            { name: '三明' },
            { name: '山南' },
            { name: '沈阳' },
            { name: '十堰' },
            { name: '神农架' },
            { name: '邵阳' },
            { name: '松原' },
            { name: '朔州' },
            { name: '三沙' },
            { name: '莎车' },
            { name: '汕头' },
        ]},
        { character: 'T', cities: [
            { name: '天津' },
            { name: '太原' },
            { name: '塔城' },
            { name: '通化' },
            { name: '通辽' },
            { name: '天水' },
            { name: '唐山' },
            { name: '台州' },
            { name: '中国台北' },
            { name: '铜仁' },
            { name: '腾冲' },
            { name: '中国台南' },
            { name: '中国台东' },
            { name: '中国台中' },
            { name: '塔什库尔干' },
            { name: '吐鲁番' },
            { name: '图木舒克' },
            { name: '泰州' },
        ]},
        { character: 'W', cities: [
            { name: '无锡' },
            { name: '武夷山' },
            { name: '乌鲁木齐' },
            { name: '五大连池' },
            { name: '潍坊' },
            { name: '武汉' },
            { name: '芜湖' },
            { name: '威海' },
            { name: '乌兰浩特' },
            { name: '万州' },
            { name: '温州' },
            { name: '梧州' },
            { name: '乌海' },
            { name: '文山' },
            { name: '乌拉特中旗' },
            { name: '武隆' },
            { name: '巫山' },
            { name: '乌兰察布' },
        ]}
    ],
    XYZ: [
        { character: 'X', cities: [
            { name: '西安' },
            { name: '厦门' },
            { name: '西双版纳' },
            { name: '中国香港' },
            { name: '西宁' },
            { name: '西昌' },
            { name: '新乡' },
            { name: '新昌' },
            { name: '襄阳' },
            { name: '夏河' },
            { name: '锡林浩特' },
            { name: '信阳' },
            { name: '徐州' },
            { name: '忻州' },
            { name: '邢台' },
            { name: '兴义' },
            { name: '新源' },
            { name: '咸阳' },
        ]},
        { character: 'Y', cities: [
            { name: '扬州' },
            { name: '延安' },
            { name: '运城' },
            { name: '宜宾' },
            { name: '宜昌' },
            { name: '伊春' },
            { name: '宜春' },
            { name: '延吉' },
            { name: '榆林' },
            { name: '伊宁' },
            { name: '烟台' },
            { name: '义乌' },
            { name: '岳阳' },
            { name: '永州' },
            { name: '伊宁' },
            { name: '玉林' },
            { name: '盐城' },
            { name: '营口' },
            { name: '于田' },
            { name: '玉树' },
        ]},
        { character: 'Z', cities: [
            { name: '郑州' },
            { name: '珠海' },
            { name: '湛江' },
            { name: '肇庆' },
            { name: '镇江' },
            { name: '张家界' },
            { name: '张家口' },
            { name: '株洲' },
            { name: '淄博' },
            { name: '遵义' },
            { name: '中山' },
        ]}
    ]
};